### ISSUE TITLE
Java exercises are complete

### ISSUE THREAD

**Issue by zierg** [krrg97/vnfm#12]
Java exercises are complete.
@krrg97 please check them out.
[Prime Factors](https://github.com/zierg/vnfm/blob/master/exercises/java/primefactors/src/main/java/primeFactors/PrimeFactors.java)
[Gilded Rose](https://github.com/zierg/vnfm/blob/master/exercises/java/gildedrose/src/main/java/com/gildedrose/GildedRose.java)

**Comment by rokr97** [comment]
Both - accepted.
