### ISSUE TITLE
[PrimeFactors] Zhuravlev's solution

### ISSUE THREAD

**Issue by zelark** [krrg97/vnfm#6]
Here is my [solution](https://github.com/zelark/vnfm/blob/zhuravlev/src/main/vnfm/kata/primefactors/zelark/PrimeFactors.java).
And [the test](https://github.com/zelark/vnfm/blob/zhuravlev/src/test/vnfm/kata/primefactors/zelark/PrimeFactorsTest.java) for it.

@krrg97, please, review it.

BTW, as I understand, we can create issues only for original repo itself without specifying particular branch.

**Comment by rokr97** [comment]
You got it right. You can specify the path in the issue's description.

Solution is accepted.
